### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dmytrunets** [Kovalchuk91/PHPAcademy_project#1]
1. Создать файл README.md проекта с описанием своего проекта + требование к системе + шаги инсталяции + другие важные моменты. (Пример https://github.com/composer/packagist/blob/master/README.md)
2. Папку vendor коммитить не надо. Для этого создать файл .gitignore и добавить папку vendor в исключения (Пример https://github.com/composer/packagist/blob/master/.gitignore). Добавить файл composer.json где в секции require указать зависимости на необходимые пакеты (twig, ...)
3. Создать файл конфигураций, в котором как минимум вынести парамерты подключения к базе данных. Пример конфигурационного файла https://github.com/composer/packagist/blob/master/app/config/config.yml#L42  Для реализации можно использовать symfony библиотеку https://github.com/symfony/config
4. Задеплоить проект на хостинг https://cpanel.hostinger.com.ua
5. Проект не поднялся ошибка 
( ! ) Catchable fatal error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in C:\OpenServer\domains\PHPAcademy_project\vendor\twig\twig\lib\Twig\Extension\Core.php on line 139 and defined in C:\OpenServer\domains\PHPAcademy_project\vendor\twig\twig\lib\Twig\Filter.php on line 35

**Comment by Kovalchuk91** [comment]
1. Добавил файл readme, удалил vendor, запушил composer.json
2. Не совсем разобрался с symfony/config, пока просто подключил парсер symfony/yaml и сделал свой класс Config по работе с ним, добавил файл Config.yml с настройками сайта и бд
3. Ошибка возникала из-за того, что twig 2.0 требовал PHP 7. Откатил на 1.0
4. Сделал изначальную установку необходимый таблиц (прописаны в файле db.sql) и профиля администратора по адресу http://{site}/install. (но не уверен, что так можно делать)
4. Проект на хостинге - [http://onliner.16mb.com](http://onliner.16mb.com) (профиль администратора - admin@test.ru:123456)

**Comment by dmytrunets** [comment]
Я рассматривал контроллер
https://github.com/Kovalchuk91/PHPAcademy_project/blob/master/App/Controllers/EventsController.php#L20
Основное что нужно переделать это весь код по работе с SQL вынести в модель. 

Тут
https://github.com/Kovalchuk91/PHPAcademy_project/blob/master/App/Controllers/EventsController.php#L65
Необходимо переписать sql который будет возвращать ту же информацию.
